conan export $PSScriptRoot/conan-recipes/gtk/all gtk/3.24.34@
conan export $PSScriptRoot/conan-recipes/gtkmm/all gtkmm/3.24.6@
conan export $PSScriptRoot/conan-recipes/autoconf/all autoconf/2.71@
conan export $PSScriptRoot/conan-recipes/openexr/3.x openexr/3.1.5@
conan export $PSScriptRoot/conan-recipes/atk/all atk/2.38.0@
conan export $PSScriptRoot/conan-recipes/glib/all glib/2.73.2@
conan export $PSScriptRoot/conan-recipes/gdk-pixbuf/all gdk-pixbuf/2.42.8@
conan export $PSScriptRoot/conan-recipes/cairo/meson cairo/1.17.4@
conan export $PSScriptRoot/conan-recipes/pango/all pango/1.50.8@
conan export $PSScriptRoot/conan-recipes/harfbuzz/all harfbuzz/5.1.0@
conan export $PSScriptRoot/conan-recipes/glibmm/all glibmm/2.66.4@
conan export $PSScriptRoot/conan-recipes/cairomm/all cairomm/1.14.3@
conan export $PSScriptRoot/conan-recipes/pangomm/all pangomm/2.46.2@
conan export $PSScriptRoot/conan-recipes/libsigcpp/2.x.x libsigcpp/2.10.8@
conan export $PSScriptRoot/conan-recipes/imagemagick/all imagemagick/7.1.0-45@
