#!/bin/sh

echo Start of post_install script.


PREFIX=$2

LIST_FILE=$PREFIX/bin/uninstall_gtk_list.txt
TEMP_FILE=tempfile.xxx

echo ARG1=$1
echo ARG2=$2
echo ARG3=$3
echo ARG4=$4
echo RESOURCE_DIR=$RESOURCE_DIR
echo PREFIX=$PREFIX
echo LIST_FILE=$LIST_FILE
echo TEMP_FILE=$TEMP_FILE
sleep 1

#[ -e  $LIST_FILE ] || { echo Unable to find $LIST_FILE ; sleep 1;  exit 1; }
cd $PREFIX
for filename in `find . | grep -e "\.la" -e "\.pc" -e -config -e "\.loaders" -e "\.immodules"` ; do {
	grep -l @PREFIX@ $filename && sed "
s;@PREFIX@;$PREFIX;g;
" < $filename > $TEMP_FILE &&
	cp $TEMP_FILE $filename && echo $filename;
} ; done

rm $TEMP_FILE

mkdir -p $PREFIX/etc/pango
[ -e $PREFIX/bin/pango-querymodules ] && $PREFIX/bin/pango-querymodules > $PREFIX/etc/pango/pango.modules

echo "Done with shell script"

exit 0



