#!/bin/sh
#
# (c) 2008, Simone Karin Lehmann, simone at lisanet dot de
# GPL version 2 or later
# script 1.3 Leo

set -e

DIR=`dirname "$0"`
cd "$DIR/../.."
APPDIR=`pwd`
cd - > /dev/null
# edit the next line to match version file
VERSION=_VERSION_
LNDIR=/tmp/skl/SynfigStudio

rm -f "$LNDIR" || true
mkdir -p /tmp/skl
chmod a+w /tmp/skl
ln -s "$APPDIR" "$LNDIR"

CWD="$LNDIR/Contents/Resources"

export PATH="$CWD/bin:$CWD/sbin:$CWD/synfig/bin:$PATH"
export SYNFIG_ROOT="$CWD/synfig/"
export SYNFIG_MODULE_LIST="$CWD/synfig/etc/synfig_modules.cfg"

echo launch

cd ~/ > /dev/null
exec "$SYNFIG_ROOT/bin/synfigstudio" "$@"

rm -f "$LNDIR" || true

echo end
