/* include/etl_profile.h.  Generated by configure.  */
/* include/etl_profile.h.in.  Generated from configure.in by autoheader.  */


#ifndef __VETL_PROFILE_H
#define __VETL_PROFILE_H

/* define if target is big endian */
#define WORDS_BIGENDIAN

#ifndef __ETL_HAS_GETTIMEOFDAY
#define __ETL_HAS_GETTIMEOFDAY
#endif

#ifndef __ETL_HAS_PTHREAD_H
#define __ETL_HAS_PTHREAD_H
#endif

#ifndef __ETL_HAS_SCHED_H
#define __ETL_HAS_SCHED_H
#endif

#ifndef __ETL_HAS_PTHREAD_CREATE
#define __ETL_HAS_PTHREAD_CREATE
#endif

#ifndef __ETL_HAS_VASPRINTF
#define __ETL_HAS_VASPRINTF
#endif

#ifndef __ETL_HAS_VSNPRINTF
#define __ETL_HAS_VSNPRINTF
#endif

#ifndef __ETL_HAS_VSPRINTF
#define __ETL_HAS_VSPRINTF
#endif

#endif // __VETL_CONFIG_H

