name: synfigstudio
title: 'Synfig Studio'
version: '1.4.0'
summary: Create and edit 2D animations and compositions
description: |
  Synfig Studio is a free and open-source 2D animation software, designed as
  powerful industrial-strength solution for creating film-quality animation
  using a vector and bitmap artwork. It eliminates the need to create
  animation frame-by frame, allowing you to produce 2D animation of a higher
  quality with fewer people and resources.

  Features:

  - Can manipulate vector and bitmap artwork
  - Automatic tweening (independent from FPS)
  - Multitude of layers of various types (geometry primitives, shapes,
  gradients, fractals)
  - Full-featured bone system
  - Filters and effects for compositing (blurs, distortions, color
  manipulation, masks)
  - All color operations use High Dynamic-Range Imaging (HDRI)
  - Pentablet-friendly tools
  - Sound support
  - Linking data on file- or parameter-level
  - Automatic animation using mathematical functions

base: core18
confinement: strict
license: GPL-3.0
grade: stable

architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64

apps:
  synfigstudio: &app
    command: usr/bin/synfigstudio
    common-id: org.synfig.SynfigStudio
    desktop: usr/share/applications/org.synfig.SynfigStudio.desktop
    extensions: [gnome-3-34]
    plugs: &plugs [opengl, home, removable-media, gsettings, network]
    environment: &env
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/gnome-platform/usr/share/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH

  synfig:
    command: usr/bin/synfig
    extensions: [gnome-3-34]
    plugs: *plugs
    environment: *env

layout:
  /usr/share/synfig:
    symlink: $SNAP/usr/share/synfig
  /usr/share/pixmaps/synfigstudio:
    symlink: $SNAP/usr/share/pixmaps/synfigstudio

parts:
  synfig-deps:
    plugin: nil
    build-packages:
      - g++
      - intltool
      - gettext
      - libmagickcore-dev
      - libmagick++-dev
      - libopenexr-dev
      - libsigc++-2.0-dev
      - libxml++2.6-dev
      - libfftw3-dev
      - libmlt-dev
      - libmlt++-dev
      - libmlt-data
      - libboost-system-dev
      - libmng-dev
      - git
    stage-packages:
      - libilmbase12
      - libmagick++-6.q16-7
      - libmagic1
      - libmlt++3
      - libmlt6
      - libmng2
      - libopenexr22
      - libsigc++-2.0-0v5
      - libxml++2.6-2v5
      - libdv-bin # mod_dv
      - ffmpeg # mod_ffmpeg
      - libflite1 # ffmpeg required
      - imagemagick # mod_imagemagick
      - libglu1-mesa
      - freeglut3
      - python3-lxml # lottie exporter

  etl:
    after: [synfig-deps]
    plugin: autotools
    source: https://github.com/synfig/synfig/releases/download/v1.4.0/ETL-1.4.0.tar.gz
    source-checksum: sha256/d43396c0ac356114713469216a9257247c2588d5475590a46db63cf201d1a011
    configflags: &cfgflags
      - --prefix=/usr

  synfig-core:
    after: [etl]
    plugin: autotools
    source: https://github.com/synfig/synfig/releases/download/v1.4.0/synfig-1.4.0.tar.gz
    source-checksum: sha256/7f36d57eba9dc959e1deae89e6908585a08db7f2d9399915a46a9eff33080c9c
    configflags: *cfgflags
    override-build: &build |
      set -xe
      autoreconf -if
      intltoolize --force
      snapcraftctl build

  synfig-studio:
    after: [synfig-core]
    plugin: autotools
    source: https://github.com/synfig/synfig/releases/download/v1.4.0/synfigstudio-1.4.0.tar.gz
    source-checksum: sha256/ca1eb1a3e2264c57974a576d1995e005079d96cee19d3dffaacded72c93fbd56
    configflags: *cfgflags
    override-build: *build
    override-stage: |
      set -xe
      snapcraftctl stage

      appdata_file="usr/share/appdata/org.synfig.SynfigStudio.appdata.xml"

      # fix the icon path and point it to a file inside the snap
      sed -i -E "s|^Icon=(.*)|Icon=\${SNAP}/usr/share/icons/hicolor/scalable/apps/\1.svg|g" \
        usr/share/applications/org.synfig.SynfigStudio.desktop

  cleanup:
    after: [synfig-studio]
    plugin: nil
    build-snaps: [core18, gnome-3-34-1804]
    override-prime: |
      set -eux
      for lib in "libharfbuzz" "libglibmm" "libgiomm" "libQt" "qt5"; do
        rm -rf "usr/lib/$SNAPCRAFT_ARCH_TRIPLET/$lib"*
      done
      for cruft in "bug" "lintian" "man" "icons/Humanity"; do
        rm -rf "$SNAPCRAFT_PRIME/usr/share/$cruft"
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
      # Remove all files from snap that are already included in the base snap or in
      # any connected content snaps
      for snap in "core18" "gnome-3-34-1804"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
